GET http://localhost:4000/user

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "xlizer",
    "email": "mustafa@mail.com",
    "passowrd": "password"
}

###

POST http://localhost:4000/login

Content-Type: application/json

{
    "email": "mustafa@mail.ru",
    "passowrd": "password"
}